from django.core.management.base import BaseCommand
from main.models import Colony

class Command(BaseCommand):
    help = 'Add sample colony data for testing'

    def handle(self, *args, **options):
        sample_colonies = [
            'Janakpuri',
            'Punjabi Bagh',
            'Kashmere Gate',
            'Rajouri Garden',
            'Dwarka',
            'Rohini',
            'Pitampura',
            'Shahdara',
            'Laxmi Nagar',
            'Mayur Vihar',
            'Saket',
            'Vasant Vihar',
            'Greater Kailash',
            'Hauz Khas',
            'Malviya Nagar',
            'Kalkaji',
            'Okhla',
            'Jangpura',
            'Lajpat Nagar',
            'Defence Colony',
            'New Friends Colony',
            'Maharani Bagh',
            'Kalkaji Extension',
            'Govindpuri',
            'Khanpur',
            'Mehrauli',
            'Vasant Kunj',
            'Uttam Nagar',
            'Vikaspuri',
            'Paschim Vihar',
            'Moti Nagar',
            'Kirti Nagar',
            'Shadipur',
            'Patel Nagar',
            'Rajendra Place',
            'Karol Bagh',
            'Paharganj',
            'Connaught Place',
            'New Delhi',
            'Old Delhi',
            'Chandni Chowk',
            'Daryaganj',
            'Jama Masjid',
            'Sadar Bazar',
            'Kashmere Gate',
            'Civil Lines',
            'Model Town',
            'Azadpur',
            'Adarsh Nagar',
            'Shalimar Bagh',
            'Wazirpur',
            'Ashok Vihar',
            'Shakurpur',
            'Rohini Sector 1',
            'Rohini Sector 2',
            'Rohini Sector 3',
            'Rohini Sector 4',
            'Rohini Sector 5',
            'Rohini Sector 6',
            'Rohini Sector 7',
            'Rohini Sector 8',
            'Rohini Sector 9',
            'Rohini Sector 10',
            'Rohini Sector 11',
            'Rohini Sector 12',
            'Rohini Sector 13',
            'Rohini Sector 14',
            'Rohini Sector 15',
            'Rohini Sector 16',
            'Rohini Sector 17',
            'Rohini Sector 18',
            'Rohini Sector 19',
            'Rohini Sector 20',
            'Rohini Sector 21',
            'Rohini Sector 22',
            'Rohini Sector 23',
            'Rohini Sector 24',
            'Rohini Sector 25',
            'Dwarka Sector 1',
            'Dwarka Sector 2',
            'Dwarka Sector 3',
            'Dwarka Sector 4',
            'Dwarka Sector 5',
            'Dwarka Sector 6',
            'Dwarka Sector 7',
            'Dwarka Sector 8',
            'Dwarka Sector 9',
            'Dwarka Sector 10',
            'Dwarka Sector 11',
            'Dwarka Sector 12',
            'Dwarka Sector 13',
            'Dwarka Sector 14',
            'Dwarka Sector 15',
            'Dwarka Sector 16',
            'Dwarka Sector 17',
            'Dwarka Sector 18',
            'Dwarka Sector 19',
            'Dwarka Sector 20',
            'Dwarka Sector 21',
            'Dwarka Sector 22',
            'Dwarka Sector 23',
            'Dwarka Sector 24',
            'Dwarka Sector 25',
            'Dwarka Sector 26',
            'Dwarka Sector 27',
            'Dwarka Sector 28',
            'Dwarka Sector 29',
            'Dwarka Sector 30',
            'Dwarka Sector 31',
            'Dwarka Sector 32',
            'Dwarka Sector 33',
            'Dwarka Sector 34',
            'Dwarka Sector 35',
            'Dwarka Sector 36',
        ]

        created_count = 0
        existing_count = 0

        for colony_name in sample_colonies:
            if not Colony.objects.filter(name__iexact=colony_name).exists():
                Colony.objects.create(name=colony_name)
                created_count += 1
            else:
                existing_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Successfully created {created_count} new colonies. '
                f'{existing_count} colonies already existed.'
            )
        ) 