# Generated by Django 5.2 on 2025-06-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='full_name',
            field=models.CharField(default='Full Name', max_length=255),
            preserve_default=False,
        ),
    ]
