# Generated by Django 5.2 on 2025-07-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
