# Generated by Django 5.2 on 2025-06-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_broker_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='expertise',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='listings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='max_deal_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='min_deal_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='broker',
            name='profile_video',
            field=models.FileField(blank=True, null=True, upload_to='profile_videos/'),
        ),
        migrations.AddField(
            model_name='broker',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
