# Generated by Django 5.2 on 2025-06-16 11:32

import main.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_broker_about_broker_achievements_broker_age_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='broker',
            managers=[
                ('objects', main.models.BrokerManager()),
            ],
        ),
    ]
