# Generated by Django 5.2 on 2025-07-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_broker_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='company_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/company/'),
        ),
        migrations.AddField(
            model_name='broker',
            name='education_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/education/'),
        ),
        migrations.AddField(
            model_name='broker',
            name='personal_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/personal/'),
        ),
    ]
