# Generated by Django 5.2.1 on 2025-06-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_broker_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='is_age_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broker',
            name='is_company_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broker',
            name='is_education_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broker',
            name='is_name_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broker',
            name='is_office_address_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broker',
            name='is_photo_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broker',
            name='is_residence_colony_verified',
            field=models.BooleanField(default=False),
        ),
    ]
