# Generated by Django 5.2 on 2025-06-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_colony'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='active_colonies',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
